"""
Generate figures similar to Figure 1 and Figure 3 from the paper:
"Refusal in Language Models Is Mediated by a Single Direction"

Figure 1: Shows the effectiveness of different refusal directions (activation addition and ablation)
Figure 3: Shows jailbreak success rates for different interventions
"""

import json
import os
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# Configuration
MODEL = "gemma-2b-it"  # Can be changed to other models: llama-2-7b-chat-hf, meta-llama-3-8b-instruct, etc.
RUNS_DIR = Path("refusal_direction/pipeline/runs")
OUTPUT_DIR = Path("hw5")

def load_json(filepath):
    """Load JSON file"""
    with open(filepath, 'r') as f:
        return json.load(f)

def generate_figure_1(model_name):
    """
    Generate Figure 1: Refusal direction selection
    Shows activation addition and ablation scores across layers
    These plots already exist but we'll document them
    """
    model_dir = RUNS_DIR / model_name / "select_direction"

    # The plots are already generated by the pipeline
    plots = {
        'actadd_scores.png': 'Adding direction on harmless instructions',
        'ablation_scores.png': 'Ablating direction on harmful instructions',
        'kl_div_scores.png': 'KL divergence scores on harmless instructions'
    }

    print(f"\n=== Figure 1 Components for {model_name} ===")
    for plot_file, description in plots.items():
        plot_path = model_dir / plot_file
        if plot_path.exists():
            print(f"✓ {description}: {plot_path}")
        else:
            print(f"✗ {description}: NOT FOUND")

    return model_dir

def generate_figure_3(model_name, output_dir):
    """
    Generate Figure 3: Jailbreak evaluation results
    Compares baseline, ablation, and activation addition across different metrics
    """
    completions_dir = RUNS_DIR / model_name / "completions"

    # Load evaluation data for harmful prompts (jailbreakbench dataset)
    baseline_eval = load_json(completions_dir / "jailbreakbench_baseline_evaluations.json")
    ablation_eval = load_json(completions_dir / "jailbreakbench_ablation_evaluations.json")
    actadd_eval = load_json(completions_dir / "jailbreakbench_actadd_evaluations.json")

    # Load evaluation data for harmless prompts
    harmless_baseline_eval = load_json(completions_dir / "harmless_baseline_evaluations.json")
    harmless_actadd_eval = load_json(completions_dir / "harmless_actadd_evaluations.json")

    # Create Figure 3: Jailbreak success rates
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Panel A: Jailbreak success on harmful prompts
    ax1 = axes[0]
    interventions = ['Baseline', 'Ablation', 'ActAdd\n(subtract)']

    # Substring matching scores
    substring_scores = [
        baseline_eval['substring_matching_success_rate'],
        ablation_eval['substring_matching_success_rate'],
        actadd_eval['substring_matching_success_rate']
    ]

    # LlamaGuard2 scores
    llamaguard_scores = [
        baseline_eval['llamaguard2_success_rate'],
        ablation_eval['llamaguard2_success_rate'],
        actadd_eval['llamaguard2_success_rate']
    ]

    x = np.arange(len(interventions))
    width = 0.35

    bars1 = ax1.bar(x - width/2, substring_scores, width, label='Substring Matching', alpha=0.8)
    bars2 = ax1.bar(x + width/2, llamaguard_scores, width, label='LlamaGuard2', alpha=0.8)

    ax1.set_ylabel('Jailbreak Success Rate')
    ax1.set_title(f'Harmful Prompts (JailbreakBench)\n{model_name}')
    ax1.set_xticks(x)
    ax1.set_xticklabels(interventions)
    ax1.legend()
    ax1.set_ylim([0, 1])
    ax1.grid(True, alpha=0.3, axis='y')

    # Add value labels on bars
    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.2f}',
                    ha='center', va='bottom', fontsize=9)

    # Panel B: Refusal rate on harmless prompts (ActAdd with +direction)
    ax2 = axes[1]
    interventions_harmless = ['Baseline', 'ActAdd\n(add)']

    # For harmless prompts, we want refusal rate (opposite of jailbreak)
    # Use substring matching refusal rate
    harmless_substring_refusal = [
        1 - harmless_baseline_eval.get('substring_matching_success_rate', 0),
        1 - harmless_actadd_eval.get('substring_matching_success_rate', 0)
    ]

    harmless_llamaguard_refusal = [
        1 - harmless_baseline_eval.get('llamaguard2_success_rate', 0),
        1 - harmless_actadd_eval.get('llamaguard2_success_rate', 0)
    ]

    x2 = np.arange(len(interventions_harmless))

    bars3 = ax2.bar(x2 - width/2, harmless_substring_refusal, width, label='Substring Matching', alpha=0.8)
    bars4 = ax2.bar(x2 + width/2, harmless_llamaguard_refusal, width, label='LlamaGuard2', alpha=0.8)

    ax2.set_ylabel('Refusal Rate')
    ax2.set_title(f'Harmless Prompts\n{model_name}')
    ax2.set_xticks(x2)
    ax2.set_xticklabels(interventions_harmless)
    ax2.legend()
    ax2.set_ylim([0, 1])
    ax2.grid(True, alpha=0.3, axis='y')

    # Add value labels on bars
    for bars in [bars3, bars4]:
        for bar in bars:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.2f}',
                    ha='center', va='bottom', fontsize=9)

    plt.tight_layout()
    output_path = output_dir / f'figure3_jailbreak_results_{model_name}.png'
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"\n✓ Generated Figure 3: {output_path}")
    plt.close()

    return output_path

def generate_loss_comparison(model_name, output_dir):
    """
    Generate additional figure: CE loss comparison
    Shows how interventions affect model performance on regular tasks
    """
    loss_dir = RUNS_DIR / model_name / "loss_evals"

    baseline_loss = load_json(loss_dir / "baseline_loss_eval.json")
    ablation_loss = load_json(loss_dir / "ablation_loss_eval.json")
    actadd_loss = load_json(loss_dir / "actadd_loss_eval.json")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    datasets = ['pile', 'alpaca']
    interventions = ['Baseline', 'Ablation', 'ActAdd']

    # Panel A: CE Loss
    ax1 = axes[0]
    loss_data = {
        'Baseline': [baseline_loss[ds]['ce_loss'] for ds in datasets],
        'Ablation': [ablation_loss[ds]['ce_loss'] for ds in datasets],
        'ActAdd': [actadd_loss[ds]['ce_loss'] for ds in datasets]
    }

    x = np.arange(len(datasets))
    width = 0.25

    for i, (intervention, losses) in enumerate(loss_data.items()):
        offset = (i - 1) * width
        bars = ax1.bar(x + offset, losses, width, label=intervention, alpha=0.8)

        # Add value labels
        for bar in bars:
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.2f}',
                    ha='center', va='bottom', fontsize=8)

    ax1.set_ylabel('Cross-Entropy Loss')
    ax1.set_title(f'CE Loss on Standard Datasets\n{model_name}')
    ax1.set_xticks(x)
    ax1.set_xticklabels(['Pile', 'Alpaca'])
    ax1.legend()
    ax1.grid(True, alpha=0.3, axis='y')

    # Panel B: Perplexity
    ax2 = axes[1]
    perplexity_data = {
        'Baseline': [baseline_loss[ds]['perplexity'] for ds in datasets],
        'Ablation': [ablation_loss[ds]['perplexity'] for ds in datasets],
        'ActAdd': [actadd_loss[ds]['perplexity'] for ds in datasets]
    }

    for i, (intervention, perplexities) in enumerate(perplexity_data.items()):
        offset = (i - 1) * width
        bars = ax2.bar(x + offset, perplexities, width, label=intervention, alpha=0.8)

        # Add value labels
        for bar in bars:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.1f}',
                    ha='center', va='bottom', fontsize=8)

    ax2.set_ylabel('Perplexity')
    ax2.set_title(f'Perplexity on Standard Datasets\n{model_name}')
    ax2.set_xticks(x)
    ax2.set_xticklabels(['Pile', 'Alpaca'])
    ax2.legend()
    ax2.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    output_path = output_dir / f'loss_comparison_{model_name}.png'
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"✓ Generated Loss Comparison: {output_path}")
    plt.close()

    return output_path

def print_summary_statistics(model_name):
    """Print summary statistics from the evaluations"""
    completions_dir = RUNS_DIR / model_name / "completions"

    print(f"\n=== Summary Statistics for {model_name} ===\n")

    # Harmful prompts
    print("Harmful Prompts (JailbreakBench):")
    for intervention in ['baseline', 'ablation', 'actadd']:
        eval_data = load_json(completions_dir / f"jailbreakbench_{intervention}_evaluations.json")
        print(f"  {intervention.capitalize()}:")
        print(f"    Substring Matching Success: {eval_data['substring_matching_success_rate']:.1%}")
        print(f"    LlamaGuard2 Success: {eval_data['llamaguard2_success_rate']:.1%}")

    # Harmless prompts
    print("\nHarmless Prompts:")
    for intervention in ['baseline', 'actadd']:
        eval_data = load_json(completions_dir / f"harmless_{intervention}_evaluations.json")
        refusal_substring = 1 - eval_data.get('substring_matching_success_rate', 0)
        refusal_llamaguard = 1 - eval_data.get('llamaguard2_success_rate', 0)
        print(f"  {intervention.capitalize()}:")
        print(f"    Substring Matching Refusal: {refusal_substring:.1%}")
        print(f"    LlamaGuard2 Refusal: {refusal_llamaguard:.1%}")

    # Loss metrics
    loss_dir = RUNS_DIR / model_name / "loss_evals"
    print("\nCross-Entropy Loss (Pile):")
    for intervention in ['baseline', 'ablation', 'actadd']:
        loss_data = load_json(loss_dir / f"{intervention}_loss_eval.json")
        print(f"  {intervention.capitalize()}: {loss_data['pile']['ce_loss']:.3f} (ppl: {loss_data['pile']['perplexity']:.1f})")

if __name__ == "__main__":
    # Create output directory
    output_dir = OUTPUT_DIR
    output_dir.mkdir(exist_ok=True)

    print("=" * 60)
    print("Generating figures from refusal direction experiments")
    print("=" * 60)

    # Generate figures for the default model
    print(f"\nUsing model: {MODEL}")

    # Figure 1: Already generated by pipeline, just document location
    fig1_dir = generate_figure_1(MODEL)

    # Figure 3: Jailbreak evaluation results
    generate_figure_3(MODEL, output_dir)

    # Additional: Loss comparison
    generate_loss_comparison(MODEL, output_dir)

    # Print statistics
    print_summary_statistics(MODEL)

    print("\n" + "=" * 60)
    print("All figures generated successfully!")
    print("=" * 60)
